name: Validate and Deploy Configurations

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Containerlab
        run: |
          curl -sL https://get.containerlab.dev | sudo bash
          containerlab version

      - name: Install Docker Images
        run: |
          docker pull ghcr.io/nokia/srlinux

      - name: Deploy topology
        run: sudo containerlab deploy -t topology/clab-topology.yaml

      - name: Validate topology
        run: |
          echo "Validating topology file"
          sudo containerlab inspect -t topology/clab-topology.yaml

      - name: Validate configuration files
        run: |
          echo "Validating configuration files"
          for config in configs/*.cfg; do
            echo "Validating $config"
          done

  deploy:
    name: Deploy to Target Server
    needs: validate
    runs-on: ubuntu-latest
    steps:

      - name: Deploy topology with Containerlab
        run: |
          mkdir -p /home/nokia-lab/
          cd /home/nokia-lab/
          sudo containerlab deploy -t topology/clab-topology.yaml
          