name: Validate and Deploy Configurations

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Containerlab
        run: |
          curl -sL https://get.containerlab.dev | sudo bash
          containerlab version

      - name: Install Docker Images
        run: |
          docker pull ghcr.io/nokia/srlinux

      - name: Validate config on SRL1
        run: sudo containerlab deploy -t topology/clab-topology.yaml

      - name: Insect CLAB Topology
        run: |
          echo "Validating topology file"
          sudo containerlab inspect -t topology/clab-topology.yaml
